/*
Made by : Alief Gilang Permana Putra
NRP : 5025221193 
Create MySQL database based on PDM from last assignment
*/

-- Create database
CREATE DATABASE invoice;
USE invoice;

-- Create tables
CREATE TABLE pelanggan(
	P_NO CHAR(5) PRIMARY KEY,
	P_NAMA VARCHAR(60) NOT NULL,
	P_JENISKELAMIN CHAR(1),
	P_TGLLAHIR DATE,
	P_ALAMAT VARCHAR(200),
	P_NOTELP VARCHAR(15),
	P_TGLDAFTAR DATE NOT NULL
);

CREATE TABLE nota(
	N_NO INT PRIMARY KEY NOT NULL,
	N_TGLMASUK DATE NOT NULL,
	N_TGLPERKIRAANSELESAI DATE NOT NULL,
	N_TGLSELESAI DATE,
	N_TGLAMBIL TIMESTAMP,
	N_STATUS VARCHAR(10) NOT NULL,
	N_KODERAK VARCHAR(3),
	PELANGGAN_P_NO CHAR(5) REFERENCES pelanggan(P_NO)  
);

CREATE TABLE payment(
	B_NO INT NOT NULL,
	B_TOTALHARGA NUMERIC(10,2) NOT NULL,
	B_TGLBAYAR DATE NOT NULL,
	NOTA_N_NO INT NOT NULL,
	PRIMARY KEY (B_NO, NOTA_N_NO),
	FOREIGN KEY (NOTA_N_NO) REFERENCES nota(N_NO)
);

CREATE TABLE jenis_layanan(
	JL_ID VARCHAR(5) NOT NULL PRIMARY KEY,
	JL_NAMA VARCHAR(100) NOT NULL,
	JL_HARGA NUMERIC(6,2) NOT NULL
);

CREATE TABLE nota_jenis_layanan(
	NOTA_N_NO INT NOT NULL,
	JENIS_LAYANAN_JL_ID VARCHAR(5) NOT NULL,
	PRIMARY KEY (NOTA_N_NO, JENIS_LAYANAN_JL_ID),
	FOREIGN KEY (NOTA_N_NO) REFERENCES nota(N_NO),
	FOREIGN KEY (JENIS_LAYANAN_JL_ID) REFERENCES jenis_layanan(JL_ID)
);

CREATE TABLE karyawan(
	K_ID CHAR(2) NOT NULL,
	K_NAMA VARCHAR(100) NOT NULL,
	K_BAGIAN VARCHAR(100),
	K_TGLMASUK DATE,
	K_EMAIL VARCHAR(100) NOT NULL,
	K_PASSWORD VARCHAR(100) NOT NULL,
	K_KOORDINATOR CHAR(2),
	PRIMARY KEY (K_ID),
	FOREIGN KEY (K_KOORDINATOR) REFERENCES karyawan(K_ID)
);

CREATE TABLE nota_karyawan(
	NOTA_N_NO INT NOT NULL,
	KARYAWAN_K_ID CHAR(2) NOT NULL,
	PRIMARY KEY (NOTA_N_NO, KARYAWAN_K_ID),
	FOREIGN KEY (NOTA_N_NO) REFERENCES nota(N_NO),
	FOREIGN KEY (KARYAWAN_K_ID) REFERENCES karyawan(K_ID)
);
